apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: sbdremediations.medik8s.medik8s.io
  annotations:
    api-approved.kubernetes.io: "https://github.com/medik8s/sbd-operator"
spec:
  group: medik8s.medik8s.io
  versions:
  - name: v1alpha1
    served: true
    storage: true
    subresources:
      status: {}
    schema:
      openAPIV3Schema:
        type: object
        description: "SBDRemediation is created by an external operator (e.g., Node Healthcheck Operator) to request SBD-based fencing for a specific unhealthy node. The SBD Operator will update its status."
        properties:
          apiVersion:
            type: string
            description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources"
          kind:
            type: string
            description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds"
          metadata:
            type: object
          spec:
            type: object
            description: "SBDRemediationSpec defines the desired state of SBDRemediation"
            required:
            - nodeName
            properties:
              nodeName:
                type: string
                description: "The name of the node to be remediated"
                minLength: 1
              reason:
                type: string
                description: "Reason specifies why this node needs to be fenced"
                enum:
                - "HeartbeatTimeout"
                - "NodeUnresponsive"
                - "ManualFencing"
                default: "NodeUnresponsive"
              timeoutSeconds:
                type: integer
                description: "TimeoutSeconds specifies how long to wait before considering the fencing failed"
                minimum: 30
                maximum: 300
                default: 60
          status:
            type: object
            description: "SBDRemediationStatus defines the observed state of SBDRemediation"
            properties:
              conditions:
                description: "Conditions represent the latest available observations of the remediation's current state"
                type: array
                items:
                  description: "Condition contains details for one aspect of the current state of this API Resource."
                  type: object
                  required:
                  - lastTransitionTime
                  - message
                  - reason
                  - status
                  - type
                  properties:
                    lastTransitionTime:
                      description: "lastTransitionTime is the last time the condition transitioned from one status to another."
                      type: string
                      format: date-time
                    message:
                      description: "message is a human readable message indicating details about the transition."
                      type: string
                      maxLength: 32768
                    observedGeneration:
                      description: "observedGeneration represents the .metadata.generation that the condition was set based upon."
                      type: integer
                      format: int64
                      minimum: 0
                    reason:
                      description: "reason contains a programmatic identifier indicating the reason for the condition's last transition."
                      type: string
                      maxLength: 1024
                      minLength: 1
                      pattern: "^[A-Za-z]([A-Za-z0-9_,:]*[A-Za-z0-9_])?$"
                    status:
                      description: "status of the condition, one of True, False, Unknown."
                      type: string
                      enum:
                      - "True"
                      - "False"
                      - Unknown
                    type:
                      description: "type of condition in CamelCase or in foo.example.com/CamelCase."
                      type: string
                      maxLength: 316
                      pattern: "^([a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*/)?(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])$"
                x-kubernetes-list-map-keys:
                - type
                x-kubernetes-list-type: map
              fenceMessageWritten:
                description: "FenceMessageWritten indicates if the fence message was successfully written to the SBD device"
                type: boolean
              lastUpdateTime:
                description: "LastUpdateTime is the time when this status was last updated"
                type: string
                format: date-time
              nodeID:
                description: "NodeID is the numeric ID assigned to the target node for SBD operations"
                type: integer
              operatorInstance:
                description: "OperatorInstance identifies which operator instance is handling this remediation"
                type: string
    additionalPrinterColumns:
    - name: Node
      type: string
      description: "The node to be remediated"
      jsonPath: .spec.nodeName
    - name: Ready
      type: string
      description: "Overall readiness of the remediation"
      jsonPath: .status.conditions[?(@.type=='Ready')].status
    - name: Fencing Succeeded
      type: string
      description: "Whether fencing completed successfully"
      jsonPath: .status.conditions[?(@.type=='FencingSucceeded')].status
    - name: NodeID
      type: integer
      description: "The numeric ID assigned to the target node"
      jsonPath: .status.nodeID
    - name: Age
      type: date
      jsonPath: .metadata.creationTimestamp
  scope: Namespaced
  names:
    plural: sbdremediations
    singular: sbdremediation
    kind: SBDRemediation
    listKind: SBDRemediationList 