# Kustomization for deploying SBD Operator without admission webhooks
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix including the one in
# crd/kustomization.yaml
# [CERTMANAGER] To enable cert-manager, uncomment all sections with 'CERTMANAGER'.
# Uncomment 'CERTMANAGER' if you encounter the following error:
# "Error from server (InternalError): error when creating "STDIN":
# Internal error occurred: failed calling webhook "webhook.cert-manager.io":
# failed to call webhook: Post "https://cert-manager-webhook.cert-manager.system.svc:443/mutate?timeout=10s":
# dial tcp 10.96.58.90:443: connect: connection refused"
# cert-manager.io/v1
# kind: Issuer
# metadata:
#   name: selfsigned-issuer
#   namespace: system
# spec:
#   selfSigned: {}
# ---
# cert-manager.io/v1
# kind: Certificate
# metadata:
#   name: serving-cert  # this name should match the one appeared in kustomizeconfig.yaml
#   namespace: system
# spec:
#   # $(SERVICE_NAME) and $(SERVICE_NAMESPACE) will be substituted by kustomize
#   dnsNames:
#   - $(SERVICE_NAME).$(SERVICE_NAMESPACE).svc
#   - $(SERVICE_NAME).$(SERVICE_NAMESPACE).svc.cluster.local
#   issuerRef:
#     kind: Issuer
#     name: selfsigned-issuer
#   secretName: webhook-server-certs # this secret will not be prefixed, since it's not managed by kustomize

resources:
- ../crd
- ../rbac
- ../manager
# [WEBHOOK] To enable webhook, uncomment the following line
# - ../webhook
# [CERTMANAGER] To enable cert-manager, uncomment the following line
# - ../certmanager

patchesStrategicMerge:
# Protect the /metrics endpoint by putting it behind auth.
# If you want your controller-manager to expose the /metrics
# endpoint w/o any authn/z, please comment the following line.
- ../default/manager_auth_proxy_patch.yaml

# [WEBHOOK] To enable webhook, uncomment the following line
# - ../default/manager_webhook_patch.yaml

# [CERTMANAGER] To enable cert-manager, uncomment the following line
# - ../default/webhookcainjection_patch.yaml 