---
apiVersion: v1
kind: Service
metadata:
  name: sbd-agent-metrics
  namespace: sbd-system
  labels:
    app: sbd-agent
    component: metrics
spec:
  type: ClusterIP
  clusterIP: None  # Headless service for DaemonSet
  selector:
    app: sbd-agent
  ports:
  - name: metrics
    port: 8080
    targetPort: 8080
    protocol: TCP
  publishNotReadyAddresses: true  # Include pods that are not ready

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: sbd-agent
  namespace: sbd-system
  labels:
    app: sbd-agent
    component: monitoring
spec:
  selector:
    matchLabels:
      app: sbd-agent
      component: metrics
  endpoints:
  - port: metrics
    interval: 30s
    path: /metrics
    scheme: http
    honorLabels: true
    # Add additional labels to identify the source
    relabelings:
    - sourceLabels: [__meta_kubernetes_pod_node_name]
      targetLabel: node
    - sourceLabels: [__meta_kubernetes_pod_name]
      targetLabel: pod
    - sourceLabels: [__meta_kubernetes_namespace]
      targetLabel: namespace
  # Optional: Specify namespaces to monitor (if different from ServiceMonitor namespace)
  namespaceSelector:
    matchNames:
    - sbd-system 