---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sbd-operator-manager-role
  labels:
    app.kubernetes.io/name: sbd-operator
    app.kubernetes.io/component: manager
    app.kubernetes.io/part-of: sbd-operator
    app.kubernetes.io/managed-by: kustomize
rules:
# Namespace management for SBD system components
# Needed to create and manage the sbd-system namespace
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["create", "get", "list", "patch", "update", "watch"]

# DaemonSet management for SBD Agent deployment
# Core functionality: deploy and manage SBD Agent pods across cluster nodes
- apiGroups: ["apps"]
  resources: ["daemonsets"]
  verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]

# Node access for node name to ID mapping and cluster topology
# Read-only access to resolve node names to node IDs for fencing operations
# NO delete/update permissions - operator cannot modify node state directly
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list", "watch"]

# Pod access for leader election and operational monitoring
# Needed for leader election mechanism and monitoring agent pods
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]

# Leader election coordination
# Required for multi-replica operator deployments to ensure single active instance
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: ["create", "get", "list", "patch", "update", "watch"]

# Event creation for observability and debugging
# Allows operator to emit events for SBDConfig and SBDRemediation operations
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch"]

# SBDConfig Custom Resource management
# Full CRUD operations for managing SBD configuration
- apiGroups: ["medik8s.medik8s.io"]
  resources: ["sbdconfigs"]
  verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]

# SBDConfig finalizer management
# Needed for proper cleanup and deletion handling
- apiGroups: ["medik8s.medik8s.io"]
  resources: ["sbdconfigs/finalizers"]
  verbs: ["update"]

# SBDConfig status updates
# Required to update the status subresource with reconciliation results
- apiGroups: ["medik8s.medik8s.io"]
  resources: ["sbdconfigs/status"]
  verbs: ["get", "patch", "update"]

# SBDRemediation Custom Resource management
# Full CRUD operations for managing fencing requests
- apiGroups: ["medik8s.medik8s.io"]
  resources: ["sbdremediations"]
  verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]

# SBDRemediation finalizer management
# Needed for proper cleanup and deletion handling of fencing operations
- apiGroups: ["medik8s.medik8s.io"]
  resources: ["sbdremediations/finalizers"]
  verbs: ["update"]

# SBDRemediation status updates
# Critical for tracking fencing operation progress and results
- apiGroups: ["medik8s.medik8s.io"]
  resources: ["sbdremediations/status"]
  verbs: ["get", "patch", "update"]

# NOTE: SBD Operator does NOT have permissions to:
# - Delete or modify nodes directly (fencing is delegated to SBD Agent)
# - Access secrets or sensitive data
# - Modify other operators or system components
# - Access resources outside the SBD system scope
#
# The operator's role is orchestration and coordination:
# 1. Deploy and manage SBD Agent DaemonSet
# 2. Process fencing requests via SBDRemediation CRs
# 3. Coordinate with SBD Agents for actual fencing execution
# 4. Provide observability through events and status updates 