---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: sbd-agent
    app.kubernetes.io/component: agent
    app.kubernetes.io/part-of: sbd-operator
    app.kubernetes.io/managed-by: sbd-operator
  name: sbd-agent
  namespace: system
automountServiceAccountToken: true 