---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: sbd-operator
    app.kubernetes.io/component: manager
    app.kubernetes.io/part-of: sbd-operator
    app.kubernetes.io/managed-by: kustomize
  name: sbd-operator-controller-manager
  namespace: system
automountServiceAccountToken: true 