# This rule is not used by the project sbd-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to medik8s.medik8s.io resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: sbd-operator
    app.kubernetes.io/managed-by: kustomize
  name: sbdconfig-viewer-role
rules:
- apiGroups:
  - medik8s.medik8s.io
  resources:
  - sbdconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - medik8s.medik8s.io
  resources:
  - sbdconfigs/status
  verbs:
  - get
