# This rule is not used by the project sbd-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over medik8s.medik8s.io.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: sbd-operator
    app.kubernetes.io/managed-by: kustomize
  name: sbdconfig-admin-role
rules:
- apiGroups:
  - medik8s.medik8s.io
  resources:
  - sbdconfigs
  verbs:
  - '*'
- apiGroups:
  - medik8s.medik8s.io
  resources:
  - sbdconfigs/status
  verbs:
  - get
