---
# Service for SBD Agent Prometheus metrics
apiVersion: v1
kind: Service
metadata:
  name: sbd-agent-metrics
  namespace: sbd-system
  labels:
    app: sbd-agent
    component: metrics
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  clusterIP: None  # Headless service for DaemonSet
  selector:
    app: sbd-agent
  ports:
  - name: metrics
    port: 8080
    targetPort: 8080
    protocol: TCP
  publishNotReadyAddresses: true  # Include pods that are not ready

---
# ServiceMonitor for Prometheus Operator
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: sbd-agent
  namespace: sbd-system
  labels:
    app: sbd-agent
    component: monitoring
spec:
  selector:
    matchLabels:
      app: sbd-agent
      component: metrics
  endpoints:
  - port: metrics
    interval: 30s
    path: /metrics
    scheme: http
    honorLabels: true
    # Add node and pod information as labels
    relabelings:
    - sourceLabels: [__meta_kubernetes_pod_node_name]
      targetLabel: node
      action: replace
    - sourceLabels: [__meta_kubernetes_pod_name]  
      targetLabel: pod
      action: replace
    - sourceLabels: [__meta_kubernetes_namespace]
      targetLabel: namespace
      action: replace
    - sourceLabels: [__meta_kubernetes_pod_host_ip]
      targetLabel: host_ip
      action: replace
    # Set job label to distinguish from other services
    - targetLabel: job
      replacement: sbd-agent
      action: replace
    metricRelabelings:
    # Keep all SBD-related metrics
    - sourceLabels: [__name__]
      regex: 'sbd_.*'
      action: keep
  # Monitor only the sbd-system namespace
  namespaceSelector:
    matchNames:
    - sbd-system 