apiVersion: medik8s.medik8s.io/v1alpha1
kind: SBDRemediation
metadata:
  labels:
    app.kubernetes.io/name: sbd-operator
    app.kubernetes.io/managed-by: kustomize
  name: sbdremediation-sample
  namespace: default
spec:
  # Name of the Kubernetes node to be fenced
  nodeName: "worker-1"
  
  # Reason for fencing (optional, defaults to NodeUnresponsive)
  reason: HeartbeatTimeout
  
  # Timeout in seconds (optional, defaults to 60)
  timeoutSeconds: 120
