apiVersion: medik8s.medik8s.io/v1alpha1
kind: SBDConfig
metadata:
  labels:
    app.kubernetes.io/name: sbd-operator
    app.kubernetes.io/managed-by: kustomize
  name: sbdconfig-sample
spec:
  # Path to the watchdog device on the host nodes
  sbdWatchdogPath: "/dev/watchdog"
  
  # Container image for the SBD Agent DaemonSet
  image: "quay.io/medik8s/sbd-agent:latest"
  
  # Namespace where the SBD Agent DaemonSet will be deployed
  namespace: "sbd-system"
